/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package edu.ucla.macroscope.emotiongraph.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the JobDocumentResult service. Represents a row in the &quot;EmotionGraph_JobDocumentResult&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link edu.ucla.macroscope.emotiongraph.model.impl.JobDocumentResultModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link edu.ucla.macroscope.emotiongraph.model.impl.JobDocumentResultImpl}.
 * </p>
 *
 * @author dave
 * @see JobDocumentResult
 * @see edu.ucla.macroscope.emotiongraph.model.impl.JobDocumentResultImpl
 * @see edu.ucla.macroscope.emotiongraph.model.impl.JobDocumentResultModelImpl
 * @generated
 */
public interface JobDocumentResultModel extends BaseModel<JobDocumentResult>,
	GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a job document result model instance should use the {@link JobDocumentResult} interface instead.
	 */

	/**
	 * Returns the primary key of this job document result.
	 *
	 * @return the primary key of this job document result
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this job document result.
	 *
	 * @param primaryKey the primary key of this job document result
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the job document result ID of this job document result.
	 *
	 * @return the job document result ID of this job document result
	 */
	public long getJobDocumentResultId();

	/**
	 * Sets the job document result ID of this job document result.
	 *
	 * @param jobDocumentResultId the job document result ID of this job document result
	 */
	public void setJobDocumentResultId(long jobDocumentResultId);

	/**
	 * Returns the job ID of this job document result.
	 *
	 * @return the job ID of this job document result
	 */
	public long getJobId();

	/**
	 * Sets the job ID of this job document result.
	 *
	 * @param jobId the job ID of this job document result
	 */
	public void setJobId(long jobId);

	/**
	 * Returns the document ID of this job document result.
	 *
	 * @return the document ID of this job document result
	 */
	public long getDocumentId();

	/**
	 * Sets the document ID of this job document result.
	 *
	 * @param documentId the document ID of this job document result
	 */
	public void setDocumentId(long documentId);

	/**
	 * Returns the line no of this job document result.
	 *
	 * @return the line no of this job document result
	 */
	public long getLineNo();

	/**
	 * Sets the line no of this job document result.
	 *
	 * @param lineNo the line no of this job document result
	 */
	public void setLineNo(long lineNo);

	/**
	 * Returns the word of this job document result.
	 *
	 * @return the word of this job document result
	 */
	@AutoEscape
	public String getWord();

	/**
	 * Sets the word of this job document result.
	 *
	 * @param word the word of this job document result
	 */
	public void setWord(String word);

	/**
	 * Returns the count of this job document result.
	 *
	 * @return the count of this job document result
	 */
	public long getCount();

	/**
	 * Sets the count of this job document result.
	 *
	 * @param count the count of this job document result
	 */
	public void setCount(long count);

	/**
	 * Returns the group ID of this job document result.
	 *
	 * @return the group ID of this job document result
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this job document result.
	 *
	 * @param groupId the group ID of this job document result
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this job document result.
	 *
	 * @return the company ID of this job document result
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this job document result.
	 *
	 * @param companyId the company ID of this job document result
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this job document result.
	 *
	 * @return the user ID of this job document result
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this job document result.
	 *
	 * @param userId the user ID of this job document result
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this job document result.
	 *
	 * @return the user uuid of this job document result
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this job document result.
	 *
	 * @param userUuid the user uuid of this job document result
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this job document result.
	 *
	 * @return the user name of this job document result
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this job document result.
	 *
	 * @param userName the user name of this job document result
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this job document result.
	 *
	 * @return the create date of this job document result
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this job document result.
	 *
	 * @param createDate the create date of this job document result
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this job document result.
	 *
	 * @return the modified date of this job document result
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this job document result.
	 *
	 * @param modifiedDate the modified date of this job document result
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(JobDocumentResult jobDocumentResult);

	@Override
	public int hashCode();

	@Override
	public CacheModel<JobDocumentResult> toCacheModel();

	@Override
	public JobDocumentResult toEscapedModel();

	@Override
	public JobDocumentResult toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}